// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:simple_calculator/firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXIOBMrBOQM5923p-roBCGwV7bLnNp5l8',
    appId: '1:44022912508:web:e78d659c9f0b3ef7fbce79',
    messagingSenderId: '44022912508',
    projectId: 'flutter-database-38d92',
    authDomain: 'flutter-database-38d92.firebaseapp.com',
    databaseURL: 'https://flutter-database-38d92.firebaseio.com',
    storageBucket: 'flutter-database-38d92.firebasestorage.app',
    measurementId: 'G-BJK05DB12L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRK4YZoZDw9rUBb_2X2r1yLFnBVmjOnYg',
    appId: '1:44022912508:android:5c5454eea848ae76fbce79',
    messagingSenderId: '44022912508',
    projectId: 'flutter-database-38d92',
    databaseURL: 'https://flutter-database-38d92.firebaseio.com',
    storageBucket: 'flutter-database-38d92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMGoDE-fPw2GpFaOKB2_sCRJK0LWwdlJU',
    appId: '1:44022912508:ios:4242ee248dfe5f43fbce79',
    messagingSenderId: '44022912508',
    projectId: 'flutter-database-38d92',
    databaseURL: 'https://flutter-database-38d92.firebaseio.com',
    storageBucket: 'flutter-database-38d92.firebasestorage.app',
    iosBundleId: 'com.example.simpleCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXIOBMrBOQM5923p-roBCGwV7bLnNp5l8',
    appId: '1:44022912508:web:bad72f5357f679d0fbce79',
    messagingSenderId: '44022912508',
    projectId: 'flutter-database-38d92',
    authDomain: 'flutter-database-38d92.firebaseapp.com',
    databaseURL: 'https://flutter-database-38d92.firebaseio.com',
    storageBucket: 'flutter-database-38d92.firebasestorage.app',
    measurementId: 'G-CNXVL3Y7NH',
  );
}
