name: Android CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-distribute:
    runs-on: ubuntu-latest
    env:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.0"
          cache: pub

      - name: Check Flutter & Dart version
        run: |
          flutter --version

      - name: Flutter clean
        run: flutter clean

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Decode Firebase service account
        run: |
          echo "${FIREBASE_SERVICE_ACCOUNT}" > service_account.json

      - name: Build APK
        run: flutter build apk --release

      - name: Distribute APK to Firebase
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
          --app <ANDROID_FIREBASE_APP_ID> \
          --groups "qa-team" \
          --token "$(cat service_account.json)"
